{"name": "test_failed", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'attach.png'", "trace": "self = <test_allure_feature.TestLogin object at 0x00000286DD88A308>\n\n    @allure.severity(allure.severity_level.NORMAL)\n    @allure.story(\"测试失败用例与用例中添加附件\")\n    @allure.link(\"https://www.cnblogs.com/linuxchao/\", name=\"bug链接\")\n    @allure.description(\"这是一个一直执行失败的测试用例\")\n    def test_failed(self):\n        \"\"\"你也可以在这里添加用例的描述信息，但是会被allure.description覆盖\"\"\"\n        try:\n>           assert False\nE           AssertionError: assert False\n\npytest_allure\\test_allure_feature.py:163: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_allure_feature.TestLogin object at 0x00000286DD88A308>\n\n    @allure.severity(allure.severity_level.NORMAL)\n    @allure.story(\"测试失败用例与用例中添加附件\")\n    @allure.link(\"https://www.cnblogs.com/linuxchao/\", name=\"bug链接\")\n    @allure.description(\"这是一个一直执行失败的测试用例\")\n    def test_failed(self):\n        \"\"\"你也可以在这里添加用例的描述信息，但是会被allure.description覆盖\"\"\"\n        try:\n            assert False\n        except AssertionError as e:\n>           with open(\"attach.png\", \"rb\") as f:\nE           FileNotFoundError: [Errno 2] No such file or directory: 'attach.png'\n\npytest_allure\\test_allure_feature.py:165: FileNotFoundError"}, "description": "这是一个一直执行失败的测试用例", "start": 1611721010494, "stop": 1611721010495, "uuid": "e0a6602e-7648-4615-b1a3-9a077fe8fe78", "historyId": "37027b7dd0680d1c6cbbfb97acb2b813", "testCaseId": "225e153463b6499706e4ab9782e9d9ba", "fullName": "pytest_allure.test_allure_feature.TestLogin#test_failed", "labels": [{"name": "severity", "value": "normal"}, {"name": "story", "value": "测试失败用例与用例中添加附件"}, {"name": "feature", "value": "登录模块"}, {"name": "parentSuite", "value": "pytest_allure"}, {"name": "suite", "value": "test_allure_feature"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PC-20200914AAyx"}, {"name": "thread", "value": "29240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_allure.test_allure_feature"}], "links": [{"type": "link", "url": "https://www.cnblogs.com/linuxchao/", "name": "bug链接"}]}